export const SEARCH_FINISHED = "SEARCHED_FINISHED";
export const SEARCH_LOAD_SUGGESTIONS_COMPLETED = "SEARCH_LOAD_SUGGESTIONS_COMPLETED";

export const RECS_LOAD_FINISHED = "RECS_LOAD_FINISHED";
export const RECS_LOAD_MORE_FINISHED = "RECS_LOAD_MORE_FINISHED";
export const SIMILAR_LOAD_FINISHED = "SIMILAR_LOAD_FINISHED";

export const PLACE_LOAD_FINISHED = "LOAD_PLACE_FINISHED";
export const PLACE_IS_LOADING = "PLACE_IS_LOADING";


export const MYPLACES_LOAD_FINISHED = "MYPLACES_LOAD_FINISHED";
export const MYPLACES_IDS_LOAD_FINISHED ="MYPLACES_IDS_LOAD_FINISHED";


export const SECRETS_LOAD_FINISHED = "SECRETS_LOAD_FINISHED";



