export const SEARCH_FINISHED = "SEARCHED_FINISHED";
export const SEARCH_LOAD_SUGGESTIONS_COMPLETED = "SEARCH_LOAD_SUGGESTIONS_COMPLETED";

export const RECS_LOAD_FINISHED = "RECS_LOAD_FINISHED";

export const PLACE_LOAD_FINISHED = "LOAD_PLACE_FINISHED";
export const PLACE_IS_LOADING = "PLACE_IS_LOADING";


export const MYPLACES_LOAD_FINISHED = "MYPLACES_LOAD_FINISHED";
export const MYPLACES_IDS_LOAD_FINISHED ="MYPLACES_IDS_LOAD_FINISHED";
export const MYPLACES_IS_LOADING = "MYPLACES_IS_LOADING";
export const MYPLACES_ADD = "MYPLACES_ADD";
export const MYPLACES_REMOVE = "MYPLACES_REMOVE";




